type User {
    _id: ID
    name: String
    username: String! @unique
    email: String! @unique
    password: String!
    role: String
    avatar: String
    joinDate: String
    isActive: Boolean
    activeCode: String
}

type Category {
    _id: ID
    title: String! @unique
    url: String! @unique
}