type User {
    _id: ID
    name: String
    username: String!
    email: String!
    password: String!
    role: String
    avatar: String
    joinDate: String
    isActive: Boolean
    activeCode: String
}

type Category {
    _id: ID
    title: String!
    url: String!
}

type Article {
    _id: ID
    summery: String!
    content: String!
    image: String!
    url: String!
    isActive: Boolean
    createdDate: String
    countView: Int
    category: Category!
    createdBy: User!
}

type Query {
  getArticles: [Article]

  names: [String]

  getCategories: [Category]
}

type Mutation {
    # authenticate
    signUp(username: String!, email: String!, password: String!): User!
    signIn(email: String!, password: String!): User!


    addCategory(title: String!, url: String!): Category!
}