type User {
    _id: ID
    name: String
    username: String!
    email: String!
    password: String!
    role: String
    avatar: String
    joinDate: String
    isActive: Boolean
    activeCode: String
}

type Category {
    _id: ID
    title: String!
    url: String!
}

type Article {
    _id: ID
    summery: String!
    content: String!
    image: String!
    url: String!
    isActive: Boolean
    createdDate: String
    countView: Int
    category: Category!
    createdBy: User!
}

type Token {
    token: String!
}

type Todo { 
    _id: ID
    content: String!
    status: Boolean!
    createdAt: String
    user: User!
}

type Note {
    _id: ID
    title: String!
    content: String!
    createdAt: String
    user: User!
}

type Query {
    getCurrentUser: User
    getArticles: [Article]
    getCategories: [Category]
    getTodos(userId: ID!): [Todo]
    getNotes(userId: ID!): [Note]
}

type Mutation {
    # authenticate
    signUp(username: String!, email: String!, password: String!): User!
    signIn(email: String!, password: String!): Token!

    # category
    addCategory(title: String!, url: String!): Category!

    # todo
    addTodo(content: String!, status: Boolean!, user: ID!): Todo

    # note
    addNote(title: String!, content: String!, user: ID!): Note
}